#!/bin/bash
# WARNING: Functions addData(), removeData() and dataIndex() are dependent on the position of the data array (below)
data=(
"/data"
)

<< "Debug"
notify() {
    zenity --notification --text="$1"
}
Debug

script=$0

addData() {
    local top="$(head -n +3 $script)"
    local middle="$@"
    local bottom="$(tail -n +4 $script)"
    echo "$top"     > $script
    echo "$middle" >> $script
    echo "$bottom" >> $script
}

removeData() {
    if [ $1 ]
    then
        echo "$(sed $1d $script)" > $script
    fi
}

dataIndex() {
    listData
    local i=0
    for elem in "${list[@]}"
    do
        if [ $(($i % 3)) -eq 1 ]
        then
            id="$elem"
        elif [ $(($i % 3)) -eq 2 ]
        then
            id+="|$elem"
            if [ "$id" = "$1" ]
            then
                echo $((($i + 10) / 3))
            fi
        fi
        ((i++))
    done
}

createEntryWindow() {
    zenity --entry                     \
           --title        "URL Manager"\
           --text         ""           \
           --entry-text   "Enter Key"  \
           --cancel-label Quit         \
           --ok-label     Enter        \
           --extra-button Edit
}

listData() {
    local i=0
    list=()
    for elem in "${data[@]}"
    do
        if [ ! $(($i % 4)) -eq 0 ]
        then
            list+=("$elem")
        fi
        ((i++))
    done
}

createListWindow() {
    listData
    zenity --list                       \
           --radiolist\
           --title        "URL Manager" \
           --text         "List of Keys"\
           --column       ""\
           --column       Key           \
           --column       Description   \
           "${list[@]}"                 \
           --print-column ALL           \
           --cancel-label Back          \
           --ok-label     Remove        \
           --extra-button Add
}

creatFormsWindow() {
    zenity --forms                  \
           --title     "URL Manager"\
	       --text      ""           \
           --separator "\" \""      \
           --add-entry URL          \
           --add-entry Key          \
           --add-entry Description
}

openURL() {
    local i=0
    for elem in "${data[@]}"
    do
        if [ $(($i % 4)) -eq 1 ]
        then
            url="$elem"
        elif [ $(($i % 4)) -eq 2 ]
        then
            if [ "${1^^}" = "${elem^^}" ]
            then
                xdg-open "$url"
            fi
        fi
        ((i++))
    done
}

openMainWindow() {
    value=$( createEntryWindow )
    status=$?

    if [ "$value" = "Edit" ]
    then
        openEditWindow
    elif [ $status -eq 0 ]
    then
        openURL "$value"
    fi
}

openEditWindow() {
    value=$( createListWindow )
    status=$?

    if [ "$value" = "Add" ]
    then
        openAddWindow
    elif [ "$status" = "0" ]
    then
        index=$( dataIndex "$value" )
        removeData $index & update
    else
        openMainWindow
    fi
}

openAddWindow() {
    value=$( creatFormsWindow )
    status=$?

    if [ $status -eq 0 ]
    then
        addData "\"FALSE\" \"$value\" \\" & update
    else
        openEditWindow
    fi
}

update() {
    sleep 0.1s
    $script "updated"
}

if [ "$1" = "updated" ]
then
    openEditWindow
else
    openMainWindow
fi
